name: Run cypress tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_FIREBASE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          CYPRESS_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          CYPRESS_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          CYPRESS_TEST_ACCOUNT_EMAIL: ${{ secrets.CYPRESS_TEST_EMAIL }}
          CYPRESS_TEST_ACCOUNT_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          start: npm start
          wait-on: "http://localhost:3000" # Waits for above
          record: true
          parallel: false # Runs test in parallel using settings above
      # # TESTING COVERAGE INFO
      # - name: Code Coverage Check
      #   run: npm run cypress:check-coverage
